### ISSUE TITLE
Graph support

### ISSUE THREAD

**Issue by 8cells** [noskovd/spring-data-orient#12]
Any possibility of use Vertices and Edges with this project?
I saw one test but it looks like not finished.

**Comment by trainings** [comment]
At the moment there is no graph-database support.
The project is likely to continue to develop in this repository https://github.com/orientechnologies/spring-data-orientdb/

I can say that for me personally support graph database is quite important. And I hope we will implement it.

**Comment by 8cells** [comment]
For me as well. Graph database without support graph - doesn`t make sense.
I can try help with that.
